targets:
  $default:
    builders:
      gql_build|ast_builder:
        enabled: true
      gql_build|schema_builder:
        enabled: true
        options:
          schema: app|lib/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
            Date:
              name: DateTime
            Time:
              name: DateTime
      gql_build|data_builder:
        enabled: true
        options:
          schema: app|lib/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
            Date:
              name: DateTime
            Time:
              name: DateTime
      gql_build|var_builder:
        enabled: true
        options:
          schema: app|lib/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
            Date:
              name: DateTime
            Time:
              name: DateTime
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: app|lib/schema.graphql
          custom_serializers:
            - import: 'package:app/date_time_serializer.dart'
              name: DateTimeSerializer
            - import: 'package:app/time_serializer.dart'
              name: TimeSerializer
      ferry_generator|req_builder:
        enabled: true
        options:
          schema: app|lib/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
            Date:
              name: DateTime
            Time:
              name: DateTime
